### PR TITLE
added dummy exercises, sections, and pictures to exercises.qmd

### PR DESCRIPTION
**Pull request by higgi13425**
minor edits to exercses.qmd

### CODE REVIEW

**Comment by shannonpileggi** [comment]
i'm not sure what issue you were having with fontawesome, the site is still deploying with correct icons

**Comment by shannonpileggi** [comment]
i'm not sure what issue you were having with fontawesome, the site is still deploying with correct icons

**Comment by shannonpileggi** [comment]
i'm wondering if we should go ahead and merge this?

**Comment by higgi13425** [comment]
Sent a PR today
    On Friday, April 21, 2023 at 03:43:05 PM EDT, Shannon Pileggi ***@***.***> wrote:  
 
 


or maybe we should set up exercises.qmd with child docs like the slides to reduce merge conflicts there, too.

**Pull request merged**
